templates: []
mode: train
resume_training: false
pilot: false
pretrained_weights: null
num_users: null
num_items: null
num_ratings: null
num_days: null
local_data_folder: ./Data
dataset_code: toys
# min_rating: 0
min_rating: 0
min_uc: 5
min_sc: 5
split: leave_one_out
dataloader_code: sas
# dataloader_random_seed: 0.0
dataloader_random_seed: 42.0
train_batch_size: 256
val_batch_size: 256
test_batch_size: 256
train_window: 100 #是什么参数?? 从尾部向前滑动的窗口大小, 目的是为了让较长的行为序列分割成多个行为序列;
dataloader_output_timestamp: false
dataloader_output_days: false
dataloader_output_user: false
train_negative_sampler_code: random #随机采样labels, sasrec的负样本从中构建;
# train_negative_sampler_code: popular #随机采样labels, sasrec的负样本从中构建;
train_negative_sample_size: 1000 #sasrec负样本中1000中随机筛选一个;
# train_negative_sampling_seed: 12345
train_negative_sampling_seed: 42
# test_negative_sampler_code: popular
test_negative_sampler_code: random
test_negative_sample_size: 100
# test_negative_sampling_seed: 98765
test_negative_sampling_seed: 42
trainer_code: sas
device: cuda
use_parallel: true
num_workers: 0
optimizer: Adam
lr: 0.001
adam_beta1: 0.9
adam_beta2: 0.999
weight_decay: 0.0
momentum: null
decay_step: 25
gamma: 1.0
clip_grad_norm: 5.0
num_epochs: -1
log_period_as_iter: 12800
metric_ks:
- 1
- 5
- 10
- 20
- 50
best_metric: NDCG@10
# saturation_wait_epochs: 20
saturation_wait_epochs: 10
model_code: gru4rec
# model_init_seed: 0
model_init_seed: 42
model_init_range: 0.02
# max_len: 200
max_len: 50
hidden_units: 64
num_blocks: 2
num_heads: 2
# num_heads: 4
# dropout: 0.2
dropout: 0.5
mask_prob: 0.2
output_info: false
residual_ln_type: pre
headtype: dot
head_use_ln: false
time_unit_divide: null
freq: 10000
tisas_max_time_intervals: null
marank_max_len: null
marank_num_att_layers: null
marank_num_linear_layers: null
absolute_kernel_types: null
relative_kernel_types: null
experiment_root: experiments
experiment_group: test
experiment_name: gru4rec_baseline_toys
wandb_project_name: null
wandb_run_name: null
wandb_run_id: null
meta: training
finetune_flag: false
add_cate_flag: false